//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace James.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int tId { get; set; }
        public Nullable<int> cId { get; set; }
        public Nullable<decimal> companyIncome { get; set; }
        public Nullable<System.DateTime> tDate { get; set; }
        public Nullable<int> rId { get; set; }
        public Nullable<decimal> restaurantIncome { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
