//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace James.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public int oId { get; set; }
        public int cId { get; set; }
        public int pId { get; set; }
        public int oQty { get; set; }
        public Nullable<System.DateTime> oDate { get; set; }
        public Nullable<System.DateTime> oRDate { get; set; }
        public int oStatus { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
